name: Build Calorie counter CI

on: [push]

jobs:
  build_ci:
    strategy:
      matrix:
        os:   [ubuntu-latest, windows-latest]
        java: [ 8, 11 ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    name: Build calorie counter CI ${{ matrix.os }} on Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
      with:
        path: caloriecounter


    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
      
    - name: Build with Gradle
      run: ./gradlew -I .github/build-scan-init.gradle build --stacktrace --scan
        
